[programs.localnet]
blog = "Ab5jcLYJ5dQUarijL1JuRJMMo321PzF9HEpf5Br1v95K"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/aabid/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
